---
- name: Install Apache on Slave-1
  hosts: 52.23.138.95
  become: true
  tasks:
  - name: Installing latest Apache
    apt:
      name: apache2
      state: present
  - name: Start Apache service 
    service:	
      name: apache2
      state: started

- name: Install ngnix on Slave-2
  hosts: 34.226.125.133
  become: true
  tasks:
  - name: Installing latest ngnix
    apt:
      name: ngnix
      state: present
  - name: Start ngnix service 
    service:	
      name: ngnix
      state: started
